### PR TITLE
Feature: tape export

### PR DESCRIPTION
**Pull request by vrishe**
Greetings, @Dotneteer. 👋  I liked your IDE pretty much, but couldn't figure out how to materialize the compiled machine code. After a few days of research I came with this approach that enables IDE users to export the compiled ZX Spectrum programs as tape files.

The feature is meant to be as follows:
First, user prepares the code/data RAM layout by either compiling the project sources or by entering them manually while interacting with virtual machine. Next, user saves the desired parts on tape. After, the saved tape buffer is exported into TZX file via 'Machine->Export SAVEd tape data' menu option.

Here it is a [new_tape.zip](https://github.com/Dotneteer/kliveide/files/12167103/new_tape.zip) file obtained the way described above. The tape is comprised of:
1. 'p' - a little program, load it as CODE
2. 'scr' - SCREEN$ picture
3. 'text' - a string of text DATA
 
In my opinion it is a reasonable trade-off as opposed to the number of the user actions required.

### CODE REVIEW

**Comment by Dotneteer** [comment]
Hi @vrishe,

Thanks for your contribution to Klive! Before merging your PR into master, I'd like to discuss a few things with you about Klive and its future, hopefully, those will be interesting for you :-)

**Please get in touch with me at dotneteer@hotmail.com to discuss those things off-channel.**

**Comment by robpearmain** [comment]
Hi

Klive3 is looking great.

Would it be possible to have the 16k spectrum as an option as well (I think
it would just be a change to have 32k instead of the 64k on the 48k model

Thanks

Rob

**Comment by Dotneteer** [comment]
Hi Rob,

Your wish is granted :-) The current master branch already has a ZX Spectrum 16K version (and a ZX Spectrum 48K NTSC version). Next week, I will create a new release with many brand-new features.

Right now, I'm working on Z88DK integration, tool and emulator scripting, and ZX Spectrum Next emulation.

Istvan

From: Rob Pearmain ***@***.***>
Date: Sunday, 7 April 2024 at 19:54
To: Dotneteer/kliveide ***@***.***>
Cc: Istvan Novak ***@***.***>, State change ***@***.***>
Subject: Re: [Dotneteer/kliveide] Feature: tape export (PR #516)
Hi

Klive3 is looking great.

Would it be possible to have the 16k spectrum as an option as well (I think
it would just be a change to have 32k instead of the 64k on the 48k model

Thanks

Rob

**Comment by robpearmain** [comment]
lol, awesome 😁👍

**Comment by Dotneteer** [comment]
Hi Rob,

I have just released Klive wioth ZX Spectrum 16K support.

https://github.com/Dotneteer/kliveide/releases/tag/v0.31.0

Istvan

From: Rob Pearmain ***@***.***>
Date: Sunday, 7 April 2024 at 20:55
To: Dotneteer/kliveide ***@***.***>
Cc: Istvan Novak ***@***.***>, State change ***@***.***>
Subject: Re: [Dotneteer/kliveide] Feature: tape export (PR #516)
lol, awesome 😁👍

**Comment by robpearmain** [comment]
Fantastic

I am going to have a play over the weekend

Thanks

Rob

**Comment by robpearmain** [comment]
Hi

Quick question, using the assembler is their a way to export/save the
binary file once assembled, and/or create tap files using the assembler
like sjasmplus

Appreciate its purpose is to inject in to the VM, but would love to use the
environment to build code from scratch and export the final tap (production
mode?), a bit like how how you create installation packages for apps in the
modern world, almost creating the final tap,as the zx “package”, including
loading screen etc.  you could almost have a file format defining different
bits of the tap, addresses, binaries to include.  For 128k, Hank switching
before loading etc

Just an idea

Awesome work on KLive

Ro

**Comment by Dotneteer** [comment]
Hi Rob,

Yes, you can export the compiled artifacts to .tap or .tzx.

When you open a Klive project, you'll have a "Project" menu with an "Export code..." item. That command displays a dialog to set up your code; it even creates the loader blocks. This dialog will automatically compile your code before the export; this is the one-stop-shop for creating tape files :-)

Istvan

From: Rob Pearmain ***@***.***>
Date: Saturday, 13 April 2024 at 09:04
To: Dotneteer/kliveide ***@***.***>
Cc: Istvan Novak ***@***.***>, State change ***@***.***>
Subject: Re: [Dotneteer/kliveide] Feature: tape export (PR #516)
Hi

Quick question, using the assembler is their a way to export/save the
binary file once assembled, and/or create tap files using the assembler
like sjasmplus

Appreciate its purpose is to inject in to the VM, but would love to use the
environment to build code from scratch and export the final tap (production
mode?), a bit like how how you create installation packages for apps in the
modern world, almost creating the final tap,as the zx “package”, including
loading screen etc. you could almost have a file format defining different
bits of the tap, addresses, binaries to include. For 128k, Hank switching
before loading etc

Just an idea

Awesome work on KLive

Ro

**Comment by robpearmain** [comment]
Incredible, great minds think alike 😂

Exciting, can’t wait to test

Rob

**Comment by robpearmain** [comment]
Looking through the export code, I was thinking it probably needs a 128k
loader where it sets the page and then loads in the 16k block, sets the
next one, using a small bit of m/c or out commands in the loader

E.g.

Clear 32768
Load “” code
Set page 6
Load “” code
Set page 8
Load “” code

Etc

So a full 128k game could be loaded.

I have some code somewhere to do this, I will dig it out

**Comment by robpearmain** [comment]
See here for example 128k loader where from the basic loader
You switch and then load, switch, load etc

https://github.com/andydansby/zx-spectrum-128k-screen-paging-sccz80

**Comment by Dotneteer** [comment]
Rob,

I have already created a loader for ZX Spectrum 128. However, it had a bug. So, I fixed it, and now, it's operational. Soon, I will create a patch release. Here are a few screenshots to display how it works (pop out them to see in full size).

See the code and running in a ZX Spectrum 128:

sp128-running


BASIC listing of the loader:

Basic-listing


Bank 0 (see the top of the dump):

Bank0

Bank 1 (see the top of the dump):

Bank1

Bank 2 - The main code segment (see the top of the dump):

Bank2

Bank 3 (see the top of the dump):

Bank3

I will notify you in this thread when the patch release is ready.

**Comment by Dotneteer** [comment]
The patch release is available: https://github.com/Dotneteer/kliveide/releases/tag/v0.31.1

**Comment by robpearmain** [comment]
Amazing.  That’s exactly what I was looking for

Thanks

**Pull request merged**
