### PR TITLE
Some IDE user experience improvements.

### PR DESCRIPTION
**Pull request by vrishe**
Here is we have now:

- 'Reveal in File Explorer' context menu option for both Project Explorer and Document Header areas;
- 'Close/Close Others/Close All' document tabs context menu options.

Context Menu has got an update that makes it easier to integrate.

### CODE REVIEW

**Comment by vrishe** [comment]
It may have some conflicts with dotneteer/fix-document-tab so we could hold the merge up for a while.

**Review by Dotneteer — CHANGES_REQUESTED** [review]
We will definitely have merge conflicts. During the weekend, I try to merge this code with the new IDE changes.

**Comment by vrishe** [comment]
This one suddenly became HUGE. We could discuss it in person if you'd like.

**Review by Dotneteer — APPROVED** [review]
I see, this is a heavy change, especially on Save and context menus. Great, keep going on :-)

**Pull request merged**
